Md gs course list
ucsb-cs156-f20/proj-ucsb-cs-las pull request #4
Opened 2020-11-13 05:28 UTC by mara-downing

Resolves #2 

Some creative decisions made: admins edit courses on the courses panel itself so they can do so while looking at courses already in place. Let me know if this was a bad idea.

2020-11-17 02:49 UTC, andrewhlu requested changes
Some small things I've noticed so far.
I only reviewed the actual code changes for now (since this PR is a bit large), I can review the tests later.

2020-11-17 02:49 UTC, andrewhlu commented on javascript/src/main/pages/Courses/Courses.js
> +// import { CourseForm } from "./CourseForm";
Can we remove this commented line?

2020-11-17 02:49 UTC, andrewhlu commented on javascript/src/main/pages/Courses/Courses.js
> +import CourseTable from "../../components/Courses/CourseTable"
Can we use absolute paths instead of relative paths?

2020-11-17 02:49 UTC, andrewhlu commented on javascript/src/main/pages/Courses/Courses.js
> +  const createCourse = buildCreateCourse(getToken, mutateCourses);
Are we using `updateCourse` and `createCourse`? These don't seem to be referenced anywhere

2020-11-17 02:49 UTC, andrewhlu commented on javascript/src/main/pages/Courses/EditCourse.js
> +import CourseForm from "../../components/Courses/CourseForm";
Absolute path instead of relative path?

2020-11-17 02:49 UTC, andrewhlu commented on javascript/src/main/pages/Courses/NewCourse.js
> +import CourseForm from "../../components/Courses/CourseForm";
Absolute path instead of relative path?

2020-11-17 02:49 UTC, andrewhlu commented on javascript/src/main/pages/Home/Home.js
> +// const courses = [{ "id": 1, "name": "CMPSC 156", "quarter": "F20", "instructorFirstName": "Phill", "instructorLastName": "Conrad", "instructorEmail": "phtcon@ucsb.edu" }];
Do we still need the comments on lines 4 and 9?

2020-11-17 02:49 UTC, andrewhlu commented on javascript/src/main/utils/fetch.js
> +// 28,29,31,32,34
Not sure what these numbers are supposed to mean

2020-11-18 19:23 UTC, scottpchow23 requested changes
A few things to clean up but other than that we can merge this.

2020-11-18 19:23 UTC, scottpchow23 commented on javascript/src/main/components/Courses/CourseForm.js
> +            createCourse(course.name, course.quarter, course.instructorFirstName, course.instructorLastName, course.instructorEmail);
This should take a course object instead of spreading the parameters out.
```suggestion
            createCourse(course);
```

2020-11-18 19:23 UTC, scottpchow23 commented on javascript/src/main/components/Courses/CourseTable.js
> +    console.log(`courses=${courses} columns=${columns}`)
I wonder if we still need this?

2020-11-18 19:23 UTC, scottpchow23 commented on javascript/src/main/components/Nav/AppNavbar.js
> +  console.log(`roleInfo=${roleInfo}`);
I wonder if we still need this?

2020-11-18 19:23 UTC, scottpchow23 commented on javascript/src/main/components/Nav/AppNavbar.js
> +  console.log(`isAdmin=${isAdmin}`);
I wonder if we still need this?

2020-11-18 19:23 UTC, scottpchow23 commented on javascript/src/main/pages/Courses/EditCourse.js
> +import { cache } from "swr"
This import can be combined with the default import for `swr` above for something like:

```jsx
import useSWR, { cache } from "swr"
```

2020-11-18 19:23 UTC, scottpchow23 commented on javascript/src/main/services/Courses/CourseService.js
> +      console.log(`err=${err}`);
I wonder if we still need this?

2020-11-18 19:23 UTC, scottpchow23 commented on javascript/src/main/services/Courses/CourseService.js
> +  const func = async (name, quarter, instructorFirstName, instructorLastName, instructorEmail) => {
The input should accept a course object instead
```suggestion
  const func = async (course) => {
```

2020-11-18 19:23 UTC, scottpchow23 commented on javascript/src/test/components/Courses/CourseForm.test.js
> +
Update the test to expect the course object
```suggestion
    expect(createCourseMock).toHaveBeenCalledWith(sampleCourse);
```

2020-11-18 19:23 UTC, scottpchow23 commented on javascript/src/test/pages/Courses/Courses.test.js
> +  });
I wonder if we still need this?

2020-11-18 19:23 UTC, scottpchow23 commented on javascript/src/test/pages/Courses/NewCourse.test.js
> +    };
I wonder if we still need this? It doesn't seem to be used.

2020-11-18 19:23 UTC, scottpchow23 commented on src/main/java/edu/ucsb/changeme/controllers/CourseController.java
> +    // course.setUserId(jwt.getSubject());
I wonder if we still need this?

2020-11-19 00:50 UTC, scottpchow23 approved these changes

2020-11-19 00:50 UTC, merged