6pm d add sorting to courses
ucsb-cs156-f20/proj-ucsb-cs-las pull request #62
Opened 2020-12-07 03:40 UTC by willmori

In this PR, we added ascending and descending sorting to various fields on the courses table.

2020-12-07 05:32 UTC, andrewhlu commented
I'm going to unassign myself from this review. Please request your team's designated LA and TA instead. Thanks!

Also, you might want to add the DS store files to the gitignore and remove them from the PR.

2020-12-08 00:03 UTC, scottpchow23 submitted a review, later dismissed
This looks good but we should remove the `.DS_Store` files and then add the following line to the `.gitignore`.

```
**/.DS_Store
```

This will prevent `.DS_Store` files from being added to the repo in the future.

2020-12-08 23:48 UTC, alejandrodiera reviewed
Looked through and everything checks out. Good work!

2020-12-11 02:50 UTC, scottpchow23 requested changes
Couple of suggestions, nearly there!

2020-12-11 02:50 UTC, scottpchow23 commented on javascript/src/main/components/Courses/CourseTable.js
> +            return (<span data-testid="sort-desc">&nbsp;&nbsp;<font color="red">{descendingON}</font>{ascendingOFF}</span>);
I'd remove the non-breaking spaces:
```suggestion
        if (!order) 
            return (<span data-testid="sort">{descendingOFF}{ascendingOFF}</span>);
        else if (order === 'asc') 
            return (<span data-testid="sort-asc">{descendingOFF}<font color="red">{ascendingON}</font></span>);
        else 
            return (<span data-testid="sort-desc"><font color="red">{descendingON}</font>{ascendingOFF}</span>);
```

2020-12-11 02:50 UTC, scottpchow23 commented on javascript/src/test/components/Courses/CourseTable.test.js
> +
Can we verify in between toggling the ascending and descending sort whether the _other_ version of each sort caret shows up? Something like this: 
```suggestion
const descendingOFF = String.fromCharCode(0x25bd);
expect(getByText(descendingOFF)).toBeInTheDocument();
```

2020-12-12 01:23 UTC, pconrad approved these changes
LGTM!

2020-12-12 01:35 UTC, merged

2020-12-12 01:35 UTC, pconrad commented
40 points!