6pm c crud tutor
ucsb-cs156-f20/proj-ucsb-cs-las pull request #68
Opened 2020-12-08 18:18 UTC by gmundewadi

This PR creates the tutor table, which has fields for "tutor id", fname, lname, email. It also contains the CRUD operations for a tutor table. There are different tiers of access to this table based on the user’s role. They are as follows: 

- Instructors have edit/delete access to all entries for their course, and view access to all entries for all courses.
- Admins have view/edit/delete access to all entries
- Members have view only access to all entries
- Guests have no access to entries in this table.

This PR also contains backend/frontend tests for all additional code written

2020-12-10 02:46 UTC, kourosh-safari approved these changes

2020-12-10 06:31 UTC, pconrad commented
Please add at least one code review from a member of the team before the staff reviews this.

2020-12-10 07:44 UTC, tenzingdsherpa approved these changes
everything looks good!

2020-12-10 07:52 UTC, parthatre reviewed
This PR looks good!

2020-12-10 07:53 UTC, parthatre approved these changes

2020-12-10 08:02 UTC, tenzingdsherpa reviewed
looks good!

2020-12-10 08:03 UTC, kourosh-safari approved these changes

2020-12-10 08:03 UTC, kourosh-safari commented on javascript/src/test/components/Tutor/TutorTable.test.js
> +// import { useHistory } from "react-router-dom";
Potentially remove these comments from production code.

2020-12-10 08:03 UTC, kourosh-safari commented on javascript/src/test/pages/Tutor/Tutor.test.js
> +  // test("can click to add a tutor", async () => {
potentially remove these comments from prod code

2020-12-10 08:03 UTC, tenzingdsherpa approved these changes
looks good!

2020-12-12 00:43 UTC, sethvanb submitted a review, later dismissed
LGTM

2020-12-12 02:47 UTC, pconrad requested changes
There is one small change that should be made... I can live with it not being made, but it would be good to make it.

2020-12-12 02:47 UTC, pconrad commented on secrets-localhost.properties.SAMPLE
> +app.admin.emails=phtcon@ucsb.edu, longhoang@umail.ucsb.edu,longhoang@ucsb.edu
Probably this should not go into the PR.

2020-12-12 03:01 UTC, sethvanb submitted a review, later dismissed

2020-12-12 03:18 UTC, pconrad requested changes
I would have been ok with this.. there were minor nitpicks, but I was willing to let them slide.

But checking a secret into the main branch.. that's a bridge too far.

This has to be fixed before it's mergeable, I'm afraid.

2020-12-12 03:18 UTC, pconrad commented on javascript/src/test/components/Tutor/TutorTable.test.js
> +// import { useHistory } from "react-router-dom";
Agreed

2020-12-12 03:18 UTC, pconrad commented on javascript/src/test/pages/Tutor/Tutor.test.js
> +  // test("can click to add a tutor", async () => {
Yes

2020-12-12 03:18 UTC, pconrad commented on secrets-heroku.properties.SAMPLE
> +auth0.clientId=p4W0HAdIJv8tMcRQ6aqLhw4NaSXd26Xg
Nooooo!!!!! we don't put secrets in the SAMPLE file that goes into GitHub!  That's the whole point of having a .SAMPLE file that is separate from the real one.

Now these secrets have to be invalidated and we have to generate new ones, doh!

2020-12-12 03:33 UTC, pconrad approved these changes
LGTM!

2020-12-12 03:34 UTC, merged

2020-12-12 03:34 UTC, pconrad commented
40 pts!