6pm b logins
ucsb-cs156-f20/proj-ucsb-cs-las pull request #71
Opened 2020-12-08 22:53 UTC by matthewwong212

mw - Frontend and backend of logins function implemented.

Todo: Test coverage for both front and back end.

2020-12-09 18:38 UTC, zhengyingl reviewed
Looks good

2020-12-09 18:51 UTC, kylekam submitted a review, later dismissed
Only thing was that the timestamp data looks slightly different in the mongodb database than in the tests, but it shouldn't impact anything

2020-12-09 18:51 UTC, kylekam commented on javascript/src/test/components/Admin/LoginTable.test.js
> +            "timestamp": "7:00",
Timestamp data looks slightly different in mongodb collections but I don't think it'll impact anything.
```suggestion
            "timestamp": "2020-12-08 14:41:48.481 -0800",
```

2020-12-09 18:51 UTC, kylekam commented on javascript/src/test/pages/Admin/ViewLogins.test.js
> +            "timestamp": "8:00",
timestamp
```suggestion
            "timestamp": "2020-12-08 14:41:48.481 -0800",
```

2020-12-09 18:51 UTC, kylekam commented on javascript/src/test/pages/Admin/ViewLogins.test.js
> +            "timestamp": "8:00",
timestamp
```suggestion
            "timestamp": "2020-12-08 14:41:48.481 -0800",
```

2020-12-09 18:51 UTC, kylekam commented on javascript/src/test/pages/Admin/ViewLogins.test.js
> +        const timestampElement = getByText(/8:00/);
timestamp
```suggestion
        const timestampElement = getByText(/2020-12-08 14:41:48.481 -0800/);
```

2020-12-09 18:51 UTC, kylekam commented on src/main/java/edu/ucsb/ucsbcslas/documents/Login.java
> +    "timestamp": "10:00",
timestamp
```suggestion
    "timestamp": "2020-12-08 14:41:48.481 -0800",
```

2020-12-10 00:29 UTC, zhengyingl approved these changes

2020-12-10 06:40 UTC, mara-downing requested changes
Everything in the code looks good.

However, the user's role (admin/member) does not appear properly either on Heroku or localhost, which should be fixed before this branch is ready to be merged into main, especially since having an admin role is necessary to be able to test the functionality of this PR.

2020-12-10 07:02 UTC, matthewwong212 commented
> 
> 
> Everything in the code looks good.
> 
> However, the user's role (admin/member) does not appear properly either on Heroku or localhost, which should be fixed before this branch is ready to be merged into main, especially since having an admin role is necessary to be able to test the functionality of this PR.

It appears to be working for me on localhost.  I've also fixed it on Heroku, though only Prof Conrad's email, and my email are registered as Admins

2020-12-10 07:21 UTC, mara-downing commented
> > Everything in the code looks good.
> > However, the user's role (admin/member) does not appear properly either on Heroku or localhost, which should be fixed before this branch is ready to be merged into main, especially since having an admin role is necessary to be able to test the functionality of this PR.
> 
> It appears to be working for me on localhost. I've also fixed it on Heroku, though only Prof Conrad's email, and my email are registered as Admins

It seems to work for me on Heroku now, thanks!

2020-12-10 07:21 UTC, mara-downing approved these changes
LGTM

2020-12-10 07:33 UTC, merged

2020-12-10 08:33 UTC, pconrad commented
40 points!