6pm d show current quarter
ucsb-cs156-f20/proj-ucsb-cs-las pull request #77
Opened 2020-12-10 08:15 UTC by ssmith563

Fixes issue 32

2020-12-10 08:46 UTC, andrewhlu commented
Looks like you're just short of 100% test coverage right now. Would you mind addressing this and re-requesting the staff tomorrow?

2020-12-10 08:48 UTC, pconrad commented
Please improve the description.  

```
Fixes issue 32
```

is not enough.  First, please use #32 so that it links to the issue.  Second please copy the user story into the issue so that the reader knows at a high level what the PR is addressing without having to go hunting for the issue.

Finally, fix the test coverage.

2020-12-10 23:14 UTC, CharityHsu requested changes
Looks good, but try adding another test because to get full coverage the if condition needs to be performed twice, for a true case and a false case. I think you might need a test where the course quarter is not the current quarter.

2020-12-10 23:14 UTC, CharityHsu commented on src/main/java/edu/ucsb/ucsbcslas/controllers/CourseController.java
> +      if(i.getQuarter().equalsIgnoreCase(currentQuarter)){
On Codecov it looks like line 100 is yellow, so might need to write a test that makes the if statement true

2020-12-11 02:21 UTC, CharityHsu submitted a review, later dismissed
Looks good, nice job figuring it out

2020-12-14 05:05 UTC, pconrad commented
Closing without merging---other teams' code have made this PR obsolete.  (The feature is already in the code base in an improved form, i.e. with setting the current quarter in the app rather than having it hard coded.)

2020-12-14 05:05 UTC, closed without merging